# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

name: mq-spring-app

replicaCount: 1
logLevel: "info"

image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 8080

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

route:
  enabled: true

ingress:
  enabled: false
  appid:
    enabled: false
    # web or app - https://cloud.ibm.com/docs/services/appid?topic=appid-kube-auth
    requestType: web

#  host: hello
  namespaceInHost: true
  subdomain: containers.appdomain.cloud
  path: "/"

#  tlsSecretName: ""

jaeger:
  enabled: false
  configName: jaeger-config
  secretName: jaeger-access
  collectorEndpoint: http://jaeger-all-in-one-inmemory-collector.openshift-operators.svc.cluster.local:14268/api/traces

vcsInfo:
  repoUrl: ""
  branch: ""

partOf: inventory

connectsTo: ""

runtime: spring

configmap:
  CHANNEL: IBM.APP.SVRCONN
  CONNECTION_NAME: qm1-ibm-mq.dev.svc.cluster.local(1414)
  QM: QM1
  QUEUE_NAME: IBM.DEMO.Q
  APP_NAME: MQ-SPRING-APP

ccdt:
  enabled: false
  # IF CCDT_URL has a value, the CHANNEL, CONNECTION_NAME, and QM are configured from CCDT
  #CCDT_URL: https://ccdt-no-security-dev.free.beeceptor.com/
  CCDT_URL: file:///ccdt/ccdt.json
  volumeName: ccdt
  volumeMountPath: "/ccdt"
  configMapName: mq-spring-app-ccdt


sealedsecret:
  PASSWORD: AgCprDoel/JdaWHzHNplzzPYoTp5wse+uNnjHol1rKLjeqYsYZpO/I9cGm5B8X271mEfQa3h8FluGiIP28EZ7bgCC+Ea8A1nFq2+Z+g+I+SDM8auy4xGHHgd2tQxz5cWy2Hpb4CVMF9GTMhSZ4F1QXojo43p+WBjAPPzGU4/AJtHBx5Oe2VZfvXd6lGcpP5Onrb94T+YT02/RW1kcQ4DWDn62XReNATbzhiXV/W4BPt2WTzXiul3VOJY5oWrwqQqFNSoZlUsb5cBSNTOm9PypIVSRY2APVWdLFsC73swPUPkIT6P07W01CToLVfdtz5lyhdmTjpJdX7+2qsaPJ05glZXSAmfzXOTgXHb7ElBg7tUuvqGBDgyPUrCMv0wo/Yvr3C2GwMJ8bfgahYxAsAy+dE5KJuwOJLhfjYw/67fDWqJQmLvL++rWTL5BHw/hhmr37Xeq0bBY88LcREFE9UBXWP3mVh/uo4xWLbR+oM0kGp304N6X8hR0VbUigXYCBNAHoPtnNN4H+GSo0BYQz8E6iByNbqvb9fLBrCix1+dHcfrQNFkbY0ROSu2iUgMhP1QI2zvhyp7EWalYlBw7/QDUPiQSWtYj4PwlF42u3Z708sbkdGAin74FmhrEv0SXnw/03wcIEibOPS30IaA2+T3exewHcB2LWcQ3CVd851mSKWR5o2899WVkNvvQJ223aU+vNZzKVE=
  USER: AgDK1nhyU+8m2877jsPnrvd7434/8MWKki4KTIm7CZQf35V53IU2267lrPxgk8djyx1hj6JraaGQPygD8951UE7paqU0yWZiFSqzBYx7pukXc8l6Fmkj3q8GmYUOgQg7qyo23Z/ZMLZs1W2yewEF0KjpWdyVK18QnQC4JSA+gftINW7qhTWgUOnVpUU4VOgR33BaBnGP2Z6WdiHNk/1PFyBz3aYfdSQhIKkH4NtsZs9ZC7yPZ1yDeiGsAFURsNe3iZV+d/FNi6M6HQU/wQORgh22bHyNABEeSHWHD5vDmpK+m/yY8aUIP5OEgiNRgI1HKSQUw0ABYLY1O58BtMQzTe7NLxN2sf749I5vl+1ZNYbOJLc/G+OxxWb6SCNYBXr4dBCMTwhXdEZdHNls0rLr9Zz/R1PI7eGgN6Bv1zi5Bl04AdoPvhnsgK4aQ1KbE93sF4c6LeTKu9xZQGpCs5YmtxGXS98r8nVvIV0616HN8Cxae+YTYKouH1HZJruJJtTVQ8Wfrqot3QEc6CjAWXXxxDM/3qVs1S/4Xnhfssnzt5eaCjrKAAZFq3aJ9Ri2HPxJJjnu8d3gQtYwOuU3V2X1ZWTNgI8MhXSnWrGY97iB8KzhOyNz31OghWTl2xRuI3Wtd/9XUFVZMHviU4LJa3uu6mSTIh882sY+GhLHvM9QkT+mek8xy/djceltom8MLh3nNJoOpnR5Cw==
  isScopeClusterWide: "true"

certs:
  volumeName: certs
  certSecretName: mq-client-jks
  certPasswordSecretName: mq-client-jks-password
  volumeMountPath: "/certs"
  trustStoreFileName: truststore.jks
  keyStoreFileName: keystore.jks

security: false

postSyncJob:
  enabled: false
