---
# Source: mq-spring-app/templates/configmap-ccdt.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: mq-spring-app-ccdt
data:
  ccdt.json: |
    {
      "channel": [
        {
          "name": "IBM.APP.SVRCONN",
          "clientConnection": {
            "connection": [
              {
                "host": "qm-dev-ibm-mq.dev.svc.cluster.local",
                "port": 1414
              }
            ],
            "queueManager": "QM1"
          },
          "type": "clientConnection"
        }
      ]
    }
